#include "opcode_name.h"
#define NO_PREFIX 4
#define PREFIX_G1 0
#define PREFIX_G2 1 // LOCK REPNE REP REPE BND
#define PREFIX_G3 2 // SEGMENT REGISTERS PREFIXES
#define PREFIX_G4 3
#define OP_INVALID 1
#define OP1_TABLE 0
#define OP2_TABLE 1
#define OP3_TABLE 2
#define OP_EXTENSION 3
#define REG_BYTE 0x40
#define SEG 0x80
#define REG_WORD 0xc0

typedef struct _opcode_mod_rm{
    int rm;
    int reg;
    int mod;
} opcode_mod_rm;

typedef struct _opcode_args{
    int arg_1_1;
    int arg_1_2;
} opcode_args;

typedef struct _opcode_info_struct{
    char opcode;
    const char *opcode_name;
    opcode_args args[3];
} opcode_info_struct;

typedef struct _opcode_extension_struct{
    const char *opcode_name;
    opcode_args args[3];
} opcode_extension_struct;

typedef struct _opcode_gathered_info{
    unsigned char prefix_table:3;
    unsigned char opcode_table:3;
    unsigned char prefix_count:2; // NUMBER OF PREFIXES BEFORE OPCODE
    unsigned int opcode_count;
    unsigned int arg_count:2;
    unsigned int opcode_len;
    unsigned char prefix;
    unsigned char opcode;
    unsigned char has_mod_rm;
    opcode_mod_rm mod_rm;
    unsigned char has_sib;
    opcode_mod_rm sib;
} opcode_gathered_info;

typedef struct _escape_opcode_struct{
    opcode_extension_struct before_bf[8];
    opcode_extension_struct after_bf[8][8];
} escape_opcode_struct;

typedef opcode_extension_struct opcode_extension_group[8];

enum abbreviation1{
    A = 1,B,C,D,E,F,G,H,I,J,L,M,N,O,P,Q,R,S,U,V,W,X,Y,Z,K,T,DR,IV,XR,EI,ST
};
/*
    Z = immediate register, regardless of op_size
    K = opcodes with changeable names
    T = Opcodes belonging to a group
    DR = Direct Register, influenced by op_size
    IV = Immediate Value
    XR = Extended-real, x87 opcodes
    EI = (14/28)w (/98/108)d bytes, x87 opcodes
    ST = ST handling, x87 opcodes 0 = ST(0), 1 = ST(x)
*/

enum abbreviation2{
    a = 1,b,c,d,dq,f,p,pd,pi,ps,q,qq,s,sd,ss,si,t,v,w,x,y,z
};

/*  w = word
    b = byte
    d = dword
    v = word, dword or qword depending on operand-size attribute
    z = word for word operand size or dword for 32 or 64 bit operand-size
*/
opcode_info_struct opcode_one[]={
    {
        '\x00',opcode_name[ADD],E,b,G,b
    },
    {
        '\x01',opcode_name[ADD],E,v,G,v
    },
    {
        '\x02',opcode_name[ADD],G,b,E,b
    },
    {
        '\x03',opcode_name[ADD],G,v,E,v
    },
    {
        '\x04',opcode_name[ADD],Z,AL|REG_BYTE,I,b
    },
    {
        '\x05',opcode_name[ADD],Z,EAX,I,z
    },
    {
        '\x06',opcode_name[PUSH],Z,ES|SEG
    },
    {
        '\x07',opcode_name[POP],Z,ES|SEG
    },
    {
        '\x08',opcode_name[OR],E,b,G,b
    },
    {
        '\x09',opcode_name[OR],E,v,G,v
    },
    {
        '\x0a',opcode_name[OR],G,b,E,b
    },
    {
        '\x0b',opcode_name[OR],G,v,E,v
    },
    {
        '\x0c',opcode_name[OR],Z,AL|REG_BYTE,I,b
    },
    {
        '\x0d',opcode_name[OR],Z,EAX,I,z
    },
    {
        '\x0e',opcode_name[PUSH],Z,CS|SEG
    },
    {
        '\x10',opcode_name[ADC],E,b,G,b
    },
    {
        '\x11',opcode_name[ADC],E,v,G,v
    },
    {
        '\x12',opcode_name[ADC],G,b,E,b
    },
    {
        '\x13',opcode_name[ADC],G,v,E,v
    },
    {
        '\x14',opcode_name[ADC],Z,AL|REG_BYTE,I,b
    },
    {
        '\x15',opcode_name[ADC],Z,EAX,I,z
    },
    {
        '\x16',opcode_name[PUSH],Z,SS|SEG
    },
    {
        '\x17',opcode_name[POP],Z,SS|SEG
    },
    {
        '\x18',opcode_name[SBB],E,b,G,b
    },
    {
        '\x19',opcode_name[SBB],E,v,G,v
    },
    {
        '\x1a',opcode_name[SBB],G,b,E,b
    },
    {
        '\x1b',opcode_name[SBB],G,v,E,v
    },
    {
        '\x1c',opcode_name[SBB],Z,AL|REG_BYTE,I,b
    },
    {
        '\x1d',opcode_name[SBB],Z,EAX,I,z
    },
    {
        '\x1e',opcode_name[PUSH],Z,DS|SEG
    },
    {
        '\x1f',opcode_name[POP],Z,DS|SEG
    },
    {
        '\x20',opcode_name[AND],E,b,G,b
    },
    {
        '\x21',opcode_name[AND],E,v,G,v
    },
    {
        '\x22',opcode_name[AND],G,b,E,b
    },
    {
        '\x23',opcode_name[AND],G,v,E,v
    },
    {
        '\x24',opcode_name[AND],Z,AL|REG_BYTE,I,b
    },
    {
        '\x25',opcode_name[AND],Z,EAX,I,z
    },
    {
        '\x27',opcode_name[DAA]
    },
    {
        '\x28',opcode_name[SUB],E,b,G,b
    },
    {
        '\x29',opcode_name[SUB],E,v,G,v
    },
    {
        '\x2a',opcode_name[SUB],G,b,E,b
    },
    {
        '\x2b',opcode_name[SUB],G,v,E,v
    },
    {
        '\x2c',opcode_name[SUB],Z,AL|REG_BYTE,I,b
    },
    {
        '\x2d',opcode_name[SUB],Z,EAX,I,z
    },
    {
        '\x2f',opcode_name[DAS]
    },
    {
        '\x30',opcode_name[XOR],E,b,G,b
    },
    {
        '\x31',opcode_name[XOR],E,v,G,v
    },
    {
        '\x32',opcode_name[XOR],G,b,E,b
    },
    {
        '\x33',opcode_name[XOR],G,v,E,v
    },
    {
        '\x34',opcode_name[XOR],Z,AL|REG_BYTE,I,b
    },
    {
        '\x35',opcode_name[XOR],Z,EAX,I,z
    },
    {
        '\x37',opcode_name[AAA]
    },
    {
        '\x38',opcode_name[CMP],E,b,G,b
    },
    {
        '\x39',opcode_name[CMP],E,v,G,v
    },
    {
        '\x3a',opcode_name[CMP],G,b,E,b
    },
    {
        '\x3b',opcode_name[CMP],G,v,E,v
    },
    {
        '\x3c',opcode_name[CMP],Z,AL|REG_BYTE,I,b
    },
    {
        '\x3d',opcode_name[CMP],Z,EAX,I,z
    },
    {
        '\x3f',opcode_name[AAS]
    },
    {
        '\x40',opcode_name[INC],Z,EAX
    },
    {
        '\x41',opcode_name[INC],Z,ECX
    },
    {
        '\x42',opcode_name[INC],Z,EDX
    },
    {
        '\x43',opcode_name[INC],Z,EBX
    },
    {
        '\x44',opcode_name[INC],Z,ESP
    },
    {
        '\x45',opcode_name[INC],Z,EBP
    },
    {
        '\x46',opcode_name[INC],Z,ESI
    },
    {
        '\x47',opcode_name[INC],Z,EDI
    },
    {
        '\x48',opcode_name[DEC],Z,EAX
    },
    {
        '\x49',opcode_name[DEC],Z,ECX
    },
    {
        '\x4a',opcode_name[DEC],Z,EDX
    },
    {
        '\x4b',opcode_name[DEC],Z,EBX
    },
    {
        '\x4c',opcode_name[DEC],Z,ESP
    },
    {
        '\x4d',opcode_name[DEC],Z,EBP
    },
    {
        '\x4e',opcode_name[DEC],Z,ESI
    },
    {
        '\x4f',opcode_name[DEC],Z,EDI
    },
    {
        '\x50',opcode_name[PUSH],Z,EAX
    },
    {
        '\x51',opcode_name[PUSH],Z,ECX
    },
    {
        '\x52',opcode_name[PUSH],Z,EDX
    },
    {
        '\x53',opcode_name[PUSH],Z,EBX
    },
    {
        '\x54',opcode_name[PUSH],Z,ESP
    },
    {
        '\x55',opcode_name[PUSH],Z,EBP
    },
    {
        '\x56',opcode_name[PUSH],Z,ESI
    },
    {
        '\x57',opcode_name[PUSH],Z,EDI
    },
    {
        '\x58',opcode_name[POP],Z,EAX
    },
    {
        '\x59',opcode_name[POP],Z,ECX
    },
    {
        '\x5a',opcode_name[POP],Z,EDX
    },
    {
        '\x5b',opcode_name[POP],Z,EBX
    },
    {
        '\x5c',opcode_name[POP],Z,ESP
    },
    {
        '\x5d',opcode_name[POP],Z,EBP
    },
    {
        '\x5e',opcode_name[POP],Z,ESI
    },
    {
        '\x5f',opcode_name[POP],Z,EDI
    },
    {
        '\x60',opcode_name[PUSHAD],K,0
    },
    {
        '\x61',opcode_name[POPAD],K,0
    },
    {
        '\x62',opcode_name[BOUND],G,v,M,a
    },
    {
        '\x63',opcode_name[ARPL],E,w,G,w
    },
    {
        '\x68',opcode_name[PUSH],I,z
    },
    {
        '\x69',opcode_name[IMUL],G,v,E,v,I,z
    },
    {
        '\x6a',opcode_name[PUSH],I,b
    },
    {
        '\x6b',opcode_name[IMUL],G,v,E,v,I,b
    },
    {
        '\x6c',opcode_name[INS],Y,b,Z,DX|REG_WORD
    },
    {
        '\x6d',opcode_name[INS],Y,z,Z,DX|REG_WORD
    },
    {
        '\x6e',opcode_name[OUTS],Z,DX|REG_WORD,X,b
    },
    {
        '\x6f',opcode_name[OUTS],Z,DX|REG_WORD,X,z
    },
    {
        '\x70',opcode_name[JO],J,b
    },
    {
        '\x71',opcode_name[JNO],J,b
    },
    {
        '\x72',opcode_name[JB],J,b
    },
    {
        '\x73',opcode_name[JNB],J,b
    },
    {
        '\x74',opcode_name[JE],J,b
    },
    {
        '\x75',opcode_name[JNE],J,b
    },
    {
        '\x76',opcode_name[JBE],J,b
    },
    {
        '\x77',opcode_name[JA],J,b
    },
    {
        '\x78',opcode_name[JS],J,b
    },
    {
        '\x79',opcode_name[JNS],J,b
    },
    {
        '\x7a',opcode_name[JP],J,b
    },
    {
        '\x7b',opcode_name[JNP],J,b
    },
    {
        '\x7c',opcode_name[JL],J,b
    },
    {
        '\x7d',opcode_name[JNL],J,b
    },
    {
        '\x7e',opcode_name[JNG],J,b
    },
    {
        '\x7f',opcode_name[JG],J,b
    },
    {
        '\x80',0,E,b,I,b,T,0
    },
    {
        '\x81',0,E,v,I,z,T,0
    },
    {
        '\x82',0,E,b,I,b,T,0
    },
    {
        '\x83',0,E,v,I,b,T,0
    },
    {
        '\x84',opcode_name[TEST],E,b,G,b
    },
    {
        '\x85',opcode_name[TEST],E,v,G,v
    },
    {
        '\x86',opcode_name[XCHG],E,b,G,b
    },
    {
        '\x87',opcode_name[XCHG],E,v,G,v
    },
    {
        '\x88',opcode_name[MOV],E,b,G,b
    },
    {
        '\x89',opcode_name[MOV],E,v,G,v
    },
    {
        '\x8a',opcode_name[MOV],G,b,E,b
    },
    {
        '\x8b',opcode_name[MOV],G,v,E,v
    },
    {
        '\x8c',opcode_name[MOV],E,w,S,w
    },
    {
        '\x8d',opcode_name[LEA],G,v,M,v
    },
    {
        '\x8e',opcode_name[MOV],S,w,E,w
    },
    {
        '\x8f',0,E,v,T,1
    },
    {
        '\x90',opcode_name[NOP]
    },
    {
        '\x91',opcode_name[XCHG],DR,EAX,DR,ECX
    },
    {
        '\x92',opcode_name[XCHG],DR,EAX,DR,EDX
    },
    {
        '\x93',opcode_name[XCHG],DR,EAX,DR,EBX
    },
    {
        '\x94',opcode_name[XCHG],DR,EAX,DR,ESP
    },
    {
        '\x95',opcode_name[XCHG],DR,EAX,DR,EBP
    },
    {
        '\x96',opcode_name[XCHG],DR,EAX,DR,ESI
    },
    {
        '\x97',opcode_name[XCHG],DR,EAX,DR,EDI
    },
    {
        '\x98',opcode_name[CWDE],K,0
    },
    {
        '\x99',opcode_name[CDQ],K,0
    },
    {
        '\x9a',opcode_name[CALL],A,p
    },
    {
        '\x9b',opcode_name[WAIT]
    },
    {
        '\x9c',opcode_name[PUSHFD],K,0
    },
    {
        '\x9d',opcode_name[POPFD],K,0
    },
    {
        '\x9e',opcode_name[SAHF]
    },
    {
        '\x9f',opcode_name[LAHF]
    },
    {
        '\xa0',opcode_name[MOV],Z,AL|REG_BYTE,O,b
    },
    {
        '\xa1',opcode_name[MOV],Z,EAX,O,v
    },
    {
        '\xa2',opcode_name[MOV],O,b,AL|REG_BYTE
    },
    {
        '\xa3',opcode_name[MOV],O,v,Z,EAX
    },
    {
        '\xa4',opcode_name[MOVS],Y,b,X,b
    },
    {
        '\xa5',opcode_name[MOVS],Y,v,X,v
    },
    {
        '\xa6',opcode_name[CMPS],X,b,Y,b
    },
    {
        '\xa7',opcode_name[CMPS],X,v,Y,v
    },
    {
        '\xa8',opcode_name[TEST],Z,AL|REG_BYTE,I,b
    },
    {
        '\xa9',opcode_name[TEST],Z,EAX,I,z
    },
    {
        '\xaa',opcode_name[STOS],Y,b,Z,AL|REG_BYTE
    },
    {
        '\xab',opcode_name[STOS],Y,v,Z,EAX
    },
    {
        '\xac',opcode_name[LODS],Z,AL|REG_BYTE,X,b
    },
    {
        '\xad',opcode_name[LODS],Z,EAX,X,v
    },
    {
        '\xae',opcode_name[SCAS],Z,AL|REG_BYTE,Y,b
    },
    {
        '\xaf',opcode_name[SCAS],Z,EAX,Y,v
    },
    {
        '\xb0',opcode_name[MOV],Z,AL|REG_BYTE,I,b
    },
    {
        '\xb1',opcode_name[MOV],Z,CL|REG_BYTE,I,b
    },
    {
        '\xb2',opcode_name[MOV],Z,DL|REG_BYTE,I,b
    },
    {
        '\xb3',opcode_name[MOV],Z,BL|REG_BYTE,I,b
    },
    {
        '\xb4',opcode_name[MOV],Z,AH|REG_BYTE,I,b
    },
    {
        '\xb5',opcode_name[MOV],Z,CH|REG_BYTE,I,b
    },
    {
        '\xb6',opcode_name[MOV],Z,DH|REG_BYTE,I,b
    },
    {
        '\xb7',opcode_name[MOV],Z,BH|REG_BYTE,I,b
    },
    {
        '\xb8',opcode_name[MOV],Z,EAX,I,v
    },
    {
        '\xb9',opcode_name[MOV],Z,ECX,I,v
    },
    {
        '\xba',opcode_name[MOV],Z,EDX,I,v
    },
    {
        '\xbb',opcode_name[MOV],Z,EBX,I,v
    },
    {
        '\xbc',opcode_name[MOV],Z,ESP,I,v
    },
    {
        '\xbd',opcode_name[MOV],Z,EBP,I,v
    },
    {
        '\xbe',opcode_name[MOV],Z,ESI,I,v
    },
    {
        '\xbf',opcode_name[MOV],Z,EDI,I,v
    },
    {
        '\xc0',0,E,b,I,b,T,2
    },
    {
        '\xc1',0,E,v,I,b,T,2
    },
    {
        '\xc2',opcode_name[RET],I,w
    },
    {
        '\xc3',opcode_name[RET]
    },
    {
        '\xc4',opcode_name[LES],G,z,M,p
    },
    {
        '\xc5',opcode_name[LDS],G,z,M,p
    },
    {
        '\xc6',0,E,b,I,b,T,11
    },
    {
        '\xc7',0,E,v,I,z,T,11
    },
    {
        '\xc8',opcode_name[ENTER],I,w,I,b
    },
    {
        '\xc9',opcode_name[LEAVE]
    },
    {
        '\xca',opcode_name[RETF],I,w
    },
    {
        '\xcb',opcode_name[RETF]
    },
    {
        '\xcc',opcode_name[INT3]
    },
    {
        '\xcd',opcode_name[INT],I,b
    },
    {
        '\xce',opcode_name[INTO]
    },
    {
        '\xcf',opcode_name[IRETD],K,0
    },
    {
        '\xd0',0,E,b,IV,1,T,2
    },
    {
        '\xd1',0,E,v,IV,1,T,2
    },
    {
        '\xd2',0,E,b,Z,CL|REG_BYTE,T,2
    },
    {
        '\xd3',0,E,v,Z,CL|REG_BYTE,T,2
    },
    {
        '\xd4',opcode_name[AAM],I,b
    },
    {
        '\xd5',opcode_name[AAD],I,b
    },
    {
        '\xd6',opcode_name[SALC]
    },
    {
        '\xd7',opcode_name[XLAT]
    },
    {
        '\xd8',0, XR, 0
    },
    {
        '\xd9',0, XR, 0
    },
    {
        '\xda',0, XR, 0
    },
    {
        '\xdb',0, XR, 0
    },
    {
        '\xdc',0, XR, 0
    },
    {
        '\xdd',0, XR, 0
    },
    {
        '\xde',0, XR, 0
    },
    {
        '\xdf',0, XR, 0
    },
    {
        '\xe0',opcode_name[LOOPDNE],J,b,K,1
    },
    {
        '\xe1',opcode_name[LOOPDE],J,b,K,1
    },
    {
        '\xe2',opcode_name[LOOPD],J,b,K,1
    },
    {
        '\xe3',opcode_name[JECXZ],J,b,K,1
    },
    {
        '\xe4',opcode_name[IN],Z,AL|REG_BYTE,I,b
    },
    {
        '\xe5',opcode_name[IN],Z,EAX,I,b
    },
    {
        '\xe6',opcode_name[OUT],I,b,Z,AL|REG_BYTE
    },
    {
        '\xe7',opcode_name[OUT],I,b,Z,EAX
    },
    {
        '\xe8',opcode_name[CALL],J,z
    },
    {
        '\xe9',opcode_name[JMP],J,z
    },
    {
        '\xea',opcode_name[JMP],A,p
    },
    {
        '\xeb',opcode_name[JMP],J,b
    },
    {
        '\xec',opcode_name[IN],Z,AL|REG_BYTE,Z,DX|REG_WORD
    },
    {
        '\xed',opcode_name[IN],Z,EAX,Z,DX|REG_WORD
    },
    {
        '\xee',opcode_name[OUT],Z,DX|REG_WORD,AL|REG_BYTE
    },
    {
        '\xef',opcode_name[OUT],Z,DX|REG_WORD,Z,EAX
    },
    {
        '\xf1',opcode_name[INT1]
    },
    {
        '\xf4',opcode_name[HLT]
    },
    {
        '\xf5',opcode_name[CMC]
    },
    {
        '\xf6',0,E,b,T,3
    },
    {
        '\xf7',0,E,v,T,3
    },
    {
        '\xf8',opcode_name[CLC]
    },
    {
        '\xf9',opcode_name[STC]
    },
    {
        '\xfa',opcode_name[CLI]
    },
    {
        '\xfb',opcode_name[STI]
    },
    {
        '\xfc',opcode_name[CLD]
    },
    {
        '\xfd',opcode_name[STD]
    },
    {
        '\xfe',0,T,4
    },
    {
        '\xff',0,T,5
    }

};
opcode_info_struct opcode_two[]={
};
opcode_info_struct opcode_three[]={
};
opcode_extension_group opcode_extension_table[]={
    { // GROUP 1
        {
            opcode_name[ADD]
        },
        {
            opcode_name[OR]
        },
        {
            opcode_name[ADC]
        },
        {
            opcode_name[SBB]
        },
        {
            opcode_name[AND]
        },
        {
            opcode_name[SUB]
        },
        {
            opcode_name[XOR]
        },
        {
            opcode_name[CMP]
        }
    }, //--GROUP 1
    { //GROUP 1A
        {
            opcode_name[POP]
        }
    }, //--GROUP 1A
    { //GROUP 2
        {
            opcode_name[ROL]
        },
        {
            opcode_name[ROR]
        },
        {
            opcode_name[RCL]
        },
        {
            opcode_name[RCR]
        },
        {
            opcode_name[SHL]
        },
        {
            opcode_name[SHR]
        },
        {
            opcode_name[SHL]
        },
        {
            opcode_name[SAR]
        }
    }, //--GROUP 2
    {//GROUP 3
        {
            opcode_name[TEST],I,z
        },
        {
            //0
        },
        {
            opcode_name[NOT]
        },
        {
            opcode_name[NEG]
        },
        {
            opcode_name[MUL],DR,EAX
        },
        {
            opcode_name[IMUL],DR,EAX
        },
        {
            opcode_name[DIV],DR,EAX
        },
        {
            opcode_name[IDIV],DR,EAX
        }
    }, //--GROUP 3
    {//GROUP 4
        {
            opcode_name[INC],E,b
        },
        {
            opcode_name[DEC],E,b
        }
    }, //--GROUP 4
    {//GROUP 5
        {
            opcode_name[INC],E,v
        },
        {
            opcode_name[DEC],E,v
        }
    },//--GROUP 5
    {//GROUP 6

    }, //--GROUP 6
    {//GROUP 7

    },//--GROUP 7
    {//GROUP 8

    },//--GROUP 8
    {//GROUP 9

    },//--GROUP 9
    {//GROUP 10

    },//--GROUP 10
    {//GROUP 11
        {
            opcode_name[MOV]
        }
    }//--GROUP 11
};
escape_opcode_struct escape_opcodes[]={
    {//D8
        {
           {
               opcode_name[FADD],XR,d
           },
           {
               opcode_name[FMUL],XR,d
           },
           {
               opcode_name[FCOM],XR,d
           },
           {
               opcode_name[FCOMP],XR,d
           },
           {
               opcode_name[FSUB],XR,d
           },
           {
               opcode_name[FSUBR],XR,d
           },
           {
               opcode_name[FDIV],XR,d
           },
           {
               opcode_name[FDIVR],XR,d
           }
        },
        {
            {
                opcode_name[FADD],ST,0,ST,1
            },
            {
                opcode_name[FMUL],ST,0,ST,1
            },
            {
                opcode_name[FCOM],ST,0,ST,1
            },
            {
                opcode_name[FCOMP],ST,0,ST,1
            },
            {
                opcode_name[FSUB],ST,0,ST,1
            },
            {
                opcode_name[FSUBR],ST,0,ST,1
            },
            {
                opcode_name[FDIV],ST,0,ST,1
            },
            {
                opcode_name[FDIVR],ST,0,ST,1
            }
        }

    }, //--D8
    {//D9
        {
            {
                opcode_name[FLD],XR,d
            },
            {
                //0
            },
            {
                opcode_name[FST],XR,d
            },
            {
                opcode_name[FSTP],XR,d
            },
            {
                opcode_name[FLDENV],EI,w
            },
            {
                opcode_name[FLDCW],XR,w
            },
            {
                opcode_name[FSTENV],EI,w
            },
            {
                opcode_name[FSTCW],XR,w
            }
        },
        {
            {
                opcode_name[FLD],ST,0,ST,1
            },
            {
                opcode_name[FXCH],ST,0,ST,1
            },
            {
                opcode_name[FNOP]
            },
            {
                //0
            },
            {
                {
                    opcode_name[FCHS]
                },
                {
                    opcode_name[FABS]
                },
                {
                    //0
                },
                {
                    //0
                },
                {
                    opcode_name[FTST]
                },
                {
                    opcode_name[FXAM]
                }
            },
            {
                {
                    opcode_name[FLD1]
                },
                {
                    opcode_name[FLDL2T]
                },
                {
                    opcode_name[FLDL2E]
                },
                {
                    opcode_name[FLDPI]
                },
                {
                    opcode_name[FLDLG2]
                },
                {
                    opcode_name[FLDLN2]
                },
                {
                    opcode_name[FLDZ]
                }
            },
            {
                {
                    opcode_name[F2XM1]
                },
                {
                    opcode_name[FYL2X]
                },
                {
                    opcode_name[FPTAN]
                },
                {
                    opcode_name[FPATAN]
                },
                {
                    opcode_name[FXTRACT]
                },
                {
                    opcode_name[FPREM1]
                },
                {
                    opcode_name[FDECSTP]
                },
                {
                    opcode_name[FINCSTP]
                }
            },
            {
                {
                    opcode_name[FPREM]
                },
                {
                    opcode_name[FYL2XP1]
                },
                {
                    opcode_name[FSQRT]
                },
                {
                    opcode_name[FSINCOS]
                },
                {
                    opcode_name[FRNDINT]
                },
                {
                    opcode_name[FSCALE]
                },
                {
                    opcode_name[FSIN]
                },
                {
                    opcode_name[FCOS]
                }
            }
        }
    },//D9
    {//DA
        {
            {
                opcode_name[FIADD],XR,d
            },
            {
                opcode_name[FIMUL],XR,d
            },
            {
                opcode_name[FICOM],XR,d
            },
            {
                opcode_name[FICOMP],XR,d
            },
            {
                opcode_name[FISUB],XR,d
            },
            {
                opcode_name[FISUBR],XR,d
            },
            {
                opcode_name[FIDIV],XR,d
            },
            {
                opcode_name[FIDIVR],XR,d
            }
        },
        {
            {
                opcode_name[FCMOVB],ST,0,ST,1
            },
            {
                opcode_name[FCMOVE],ST,0,ST,1
            },
            {
                opcode_name[FCMOVBE],ST,0,ST,1
            },
            {
                opcode_name[FCMOVU],ST,0,ST,1
            },
            {
                //0
            },
            {
                {
                    //0
                },
                {
                    opcode_name[FUCOMPP]
                }
            }
        }
    },//DA
    {//DB
        {
            {
                opcode_name[FILD],XR,d
            },
            {
                opcode_name[FISTTP],XR,d
            },
            {
                opcode_name[FIST],XR,d
            },
            {
                opcode_name[FISTP],XR,d
            },
            {
                //0
            },
            {
                opcode_name[FLD],XR,t
            },
            {
                //0
            },
            {
                opcode_name[FSTP],XR,t
            }
        },
        {
            {
                opcode_name[FCMOVNB],ST,0,ST,1
            },
            {
                opcode_name[FCMOVNE],ST,0,ST,1
            },
            {
                opcode_name[FCMOVNBE],ST,0,ST,1
            },
            {
                opcode_name[FCMOVNU],ST,0,ST,1
            },
            {
                {
                    opcode_name[FENI]
                },
                {
                    opcode_name[FDISI]
                },
                {
                    opcode_name[FCLEX]
                },
                {
                    opcode_name[FINIT]
                }
            },
            {
                opcode_name[FUCOMI],ST,0,ST,1
            },
            {
                opcode_name[FCOMI],ST,0,ST,1
            }
        }
    },//DB
    {//DC
        {
            {
                opcode_name[FADD],XR,q
            },
            {
                opcode_name[FMUL],XR,q
            },
            {
                opcode_name[FCOM],XR,q
            },
            {
                opcode_name[FCOMP],XR,q
            },
            {
                opcode_name[FSUB],XR,q
            },
            {
                opcode_name[FSUBR],XR,q
            },
            {
                opcode_name[FDIV],XR,q
            },
            {
                opcode_name[FDIVR],XR,q
            }
        },
        {
            {
                opcode_name[FADD],ST,1,ST,0
            },
            {
                opcode_name[FMUL],ST,1,ST,0
            },
            {
                //0
            },
            {
                //0
            },
            {
                opcode_name[FSUBR],ST,1,ST,0
            },
            {
                opcode_name[FSUB],ST,1,ST,0
            },
            {
                opcode_name[FDIVR],ST,1,ST,0
            },
            {
                opcode_name[FDIV],ST,1,ST,0
            }
        }
    },//DC
    {//DD
        {
            {
                opcode_name[FLD],XR,q
            },
            {
                opcode_name[FISTTP],XR,q
            },
            {
                opcode_name[FST],XR,q
            },
            {
                opcode_name[FSTP],XR,q
            },
            {
                opcode_name[FRSTOR],EI,d
            },
            {
                //0
            },
            {
                opcode_name[FSAVE],EI,d
            },
            {
                opcode_name[FSTSW],XR,w
            }
        },
        {
            {
                opcode_name[FFREE],ST,1
            },
            {
                //0
            },
            {
                opcode_name[FST],ST,1
            },
            {
                opcode_name[FSTP],ST,1
            },
            {
                opcode_name[FUCOM],ST,1,ST,0
            },
            {
                opcode_name[FUCOMP],ST,1
            }
        }
    },//DD
    {//DE
        {
            {
                opcode_name[FIADD],XR,w
            },
            {
                opcode_name[FIMUL],XR,w
            },
            {
                opcode_name[FICOM],XR,w
            },
            {
                opcode_name[FICOMP],XR,w
            },
            {
                opcode_name[FISUB],XR,w
            },
            {
                opcode_name[FISUBR],XR,w
            },
            {
                opcode_name[FIDIV],XR,w
            },
            {
                opcode_name[FIDIVR],XR,w
            }
        },
        {
            {
                opcode_name[FADDP],ST,1,ST,0
            },
            {
                opcode_name[FMULP],ST,1,ST,0
            },
            {
                //0
            },
            {
                {
                    //0
                },
                {
                    opcode_name[FCOMPP]
                }
            },
            {
                opcode_name[FSUBRP],ST,1,ST,0
            },
            {
                opcode_name[FSUBP],ST,1,ST,0
            },
            {
                opcode_name[FDIVRP],ST,1,ST,0
            },
            {
                opcode_name[FDIVP],ST,1,ST,0
            }
        }
    },//DE
    {//DF
        {
            {
                opcode_name[FILD],XR,w
            },
            {
                opcode_name[FISTTP],XR,w
            },
            {
                opcode_name[FIST],XR,w
            },
            {
                opcode_name[FISTP],XR,w
            },
            {
                opcode_name[FBLD],XR,t
            },
            {
                opcode_name[FILD],XR,q
            },
            {
                opcode_name[FBSTP],XR,t
            },
            {
                opcode_name[FISTP],XR,q
            }
        },
        {
            {
                //0
            },
            {
                //0
            },
            {
                //0
            },
            {
                //0
            },
            {
                opcode_name[FSTSW],Z,AX|REG_WORD
            },
            {
                opcode_name[FUCOMIP],ST,0,ST,1
            },
            {
                opcode_name[FCOMIP],ST,0,ST,1
            }
        }
    }//DF
};
int opcode_table_size[]={
    sizeof(opcode_one), sizeof(opcode_two), sizeof(opcode_three)
};
opcode_info_struct *opcode_table[]={
    opcode_one, opcode_two, opcode_three
};
